version: '3'

tasks:
  default:
    desc: タスク一覧を表示
    cmds:
      - task --list
    silent: true

  check:all:
    desc: すべてのプロジェクトのチェックを実行
    dir: "{{.ROOT_DIR}}"
    cmds:
      - cd shared/module1 && task check
      # 他のプロジェクトが追加された場合は、ここに追加していく
    silent: false

  lint:all:
    desc: すべてのプロジェクトの静的解析を実行
    dir: "{{.ROOT_DIR}}"
    cmds:
      - cd shared/module1 && task lint
      # 他のプロジェクトが追加された場合は、ここに追加していく
    silent: false

  format:all:
    desc: すべてのプロジェクトのフォーマットを実行
    dir: "{{.ROOT_DIR}}"
    cmds:
      - cd shared/module1 && task format
      # 他のプロジェクトが追加された場合は、ここに追加していく
    silent: false

  test:all:
    desc: すべてのプロジェクトのテストを実行
    dir: "{{.ROOT_DIR}}"
    cmds:
      - cd shared/module1 && task test
      # 他のプロジェクトが追加された場合は、ここに追加していく
    silent: false 